import { Action, a2ui } from "../../../../../packages/a2ui-core/src";

export async function GET() {
  const surface = a2ui.surface({
    id: "agent-generated-reservation",
    title: "Agent Generated Reservation UI",
    components: [
      a2ui.heading("Book a Table"),
      a2ui.form({
        title: "Reservation Details",
        submit: Action.submit("reservation.create"),
        children: [
          a2ui.input("Name", "/reservation/name"),
          a2ui.input("Date", "/reservation/date"),
          a2ui.input("Guests", "/reservation/guests")
        ]
      })
    ]
  });

  const payload = a2ui.response({
    message: "Payload generated by the A2UI agent endpoint.",
    surface
  });

  return Response.json(payload);
}
